@startuml
interface Prestable
interface Renovable
interface Reservable
interface Descargable
interface Distribuible
interface Restaurable

class EjemplarFisico
class EjemplarDigital

Prestable <|.. EjemplarFisico
Renovable <|.. EjemplarFisico
Reservable <|.. EjemplarFisico
Restaurable <|.. EjemplarFisico

Prestable <|.. EjemplarDigital
Descargable <|.. EjemplarDigital
Distribuible <|.. EjemplarDigital
@enduml
